deploy-prod:
  stage: deploy
  script:
    - ls
    - pwd
    - echo -e "http://mirrors.aliyun.com/alpine/v3.10/main/" > /etc/apk/repositories
    - apk add sshpass

    - apk add nodejs
    - node -v
    - apk add npm
    - npm -v
    - npm config set registry https://registry.npm.taobao.org
    - npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
    - npm install
    - npm run build

    - mv dist VGDS
    - apk add openssh-client
    - rm -rf /var/lib/apt/lists/*
    - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    - echo " UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config
    - pwd
    - ls
    - sshpass -p $bbhostpw scp -r VGDS bit@$bbhostip:$location
